### ISSUE TITLE
拓展无效

### ISSUE THREAD

**Issue by BlueDancers** [vueComponent/ant-design-vue-helper#23]
电脑版本：mac 13.1 (22C65)
vscode 版本：1.74.3
项目环境：通过npm init vue@latest生成的vue3项目

安装拓展后，在.vue文件中输出 <a- ，不存在任何代码提示

使用快捷键shift + command + i，vscode报错command 'antdv-helper.search' not found

拓展的运行时状态为：尚未激活

麻烦大佬有空处理一下

**Comment by helloqinsong** [comment]
我也遇到同样的问题，麻烦来大佬处理一下
